<a href="https://colab.research.google.com/github/parvvaresh/Neural-Networks/blob/main/MNIST%20Datasets/The_MNIST_Dataset_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

In [ ]:
#load digits
X, y = load_digits(n_class = 10, return_X_y = True)

In [ ]:
print(f"x row is {X.shape[0]} --- x columns is : {X.shape[1]}")
print("---------------------------------------------------------")
print(f"y row is {y.shape[0]} --- y columns is : {1}")

x row is 1797 --- x columns is : 64
---------------------------------------------------------
y row is 1797 --- y columns is : 1


In [ ]:
#make test and train

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 2)

In [ ]:
#create a model and fit

model = MLPClassifier(random_state = 2)

model.fit(X_train, y_train)

MLPClassifier(random_state=2)

In [ ]:
#score

print(f"score of this model : {model.score(X_test, y_test)}")

score of this model : 0.96


In [ ]:
#find how many data wrong predict

all_X_test = X_test.shape[0]

score = model.score(X_test, y_test)
print(f"number of wrong predict is {all_X_test * (1 - score)}")

number of wrong predict is 18.000000000000014


In [ ]:
#see 


y_pred = model.predict(X_test)
incorrect = X_test[y_pred != y_test]
incorrect_true = y_test[y_pred != y_test]
incorrect_pred = y_pred[y_pred != y_test]

j = 0
print(incorrect[j].reshape(8, 8).astype(int))
print("true value:", incorrect_true[j])
print("predicted value:", incorrect_pred[j])

[[ 0  0 11  7  0  0  0  0]
 [ 0  5 16  3  2 14  3  0]
 [ 0  9 15  0 12 15  0  0]
 [ 0  6 16 15 16  5  0  0]
 [ 0  0  6 15 11  0  0  0]
 [ 0  0  1 16  4  0  0  0]
 [ 0  0  9 12  0  0  0  0]
 [ 0  0 13 10  0  0  0  0]]
true value: 4
predicted value: 9
